version: '3'

services:
  postgres:
    container_name: community-postgres
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db.postgres

  # redis:
  #   container_name: community-redis
  #   image: redis:6-alpine
